# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d5de3482ae6ee30e82682d4bbe24a10f2fd75f2fd5577eb34a0a33ec5c49ec75a5928cb24c15a5f074c25048f2ebd8a18a01cc1a0cca911dccd1add31a335d9

test:
  secret_key_base: 6c8f8c40c13c9c061d8650568302887b4954dbc3425eccaef592d1e373a07b48233c229782401dc6e7e1c7d4399c5a80ce6751fa0bb738f0acc33425ae5f72ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
